[TAIPY]

[DATA_NODE.input]
default_data = "21:int"

[DATA_NODE.output]

[TASK.double]
function = "__main__.double:function"
inputs = [ "input:SECTION",]
outputs = [ "output:SECTION",]
skippable = "False:bool"

[SCENARIO.my_scenario]
tasks = [ "double:SECTION",]
additional_data_nodes = []

[SCENARIO.my_scenario.comparators]

[SCENARIO.my_scenario.sequences]
