[TAIPY]

[DATA_NODE.historical_data]
storage_type = "csv"
default_path = "time_series.csv"

[DATA_NODE.month_data]

[DATA_NODE.nb_of_values]

[TASK.filter_current]
function = "__main__.filter_current:function"
inputs = [ "historical_data:SECTION",]
outputs = [ "month_data:SECTION",]
skippable = "False:bool"

[TASK.count_values]
function = "__main__.count_values:function"
inputs = [ "month_data:SECTION",]
outputs = [ "nb_of_values:SECTION",]
skippable = "False:bool"

[SCENARIO.my_scenario]
tasks = [ "filter_current:SECTION", "count_values:SECTION",]
additional_data_nodes = []

[SCENARIO.my_scenario.comparators]

[SCENARIO.my_scenario.sequences]
